# Site settings
title: Christopher F. Viceconte
email: CFViceconte@gmail.com
url: https://pleasegod.help
description: "Novelist | Literati | Illuminati"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#cccccc'

# Footer settings
footer: Christopher F. Viceconte

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/cfviceconte
  - title: facebook
    url: https://www.facebook.com/CFViceconte/
  - title: instagram
    url: https://www.instagram.com/youngveezyofficial/

# Build settings
markdown: kramdown
permalink: pretty
